const sampleTasks = [
  // Developer Mahesh
  {
    title: "Refactor authentication module",
    description: "Improve JWT token refresh logic for better security",
    priority: "High",
    status: "in_Progress",
    dueDate: new Date("2025-08-10"),
    tags: "backend,auth,security",
    inProgress: 40,
    user: "6890e52b9b49d5adb9e8a3aa",
  },
  {
    title: "Design landing page",
    description: "Create a responsive landing page using Tailwind CSS",
    priority: "Medium",
    status: "todo",
    dueDate: new Date("2025-08-12"),
    tags: "frontend,ui,tailwind",
    inProgress: 0,
    user: "6890e52b9b49d5adb9e8a3aa",
  },
  {
    title: "Set up CI/CD pipeline",
    description: "Configure GitHub Actions for automated deployment",
    priority: "High",
    status: "todo",
    dueDate: new Date("2025-08-15"),
    tags: "devops,ci,github",
    inProgress: 0,
    user: "6890e52b9b49d5adb9e8a3aa",
  },
  {
    title: "Write unit tests for task service",
    description: "Add test cases for all task service methods",
    priority: "Medium",
    status: "done",
    dueDate: new Date("2025-08-03"),
    tags: "testing,jest,backend",
    inProgress: 100,
    user: "6890e52b9b49d5adb9e8a3aa",
  },
  {
    title: "Optimize MongoDB indexes",
    description: "Add appropriate indexes to improve read performance",
    priority: "Low",
    status: "in_Progress",
    dueDate: new Date("2025-08-18"),
    tags: "mongo,performance,backend",
    inProgress: 20,
    user: "6890e52b9b49d5adb9e8a3aa",
  },

  // Coder
  {
    title: "Implement drag-and-drop tasks",
    description: "Enable users to rearrange tasks on dashboard",
    priority: "High",
    status: "in_Progress",
    dueDate: new Date("2025-08-09"),
    tags: "frontend,ux,drag",
    inProgress: 70,
    user: "6894bf94ff89b80345c155b1",
  },
  {
    title: "Fix bug in calendar sync",
    description: "Resolve issue where tasks are not syncing with calendar",
    priority: "Medium",
    status: "todo",
    dueDate: new Date("2025-08-13"),
    tags: "calendar,bugfix,api",
    inProgress: 0,
    user: "6894bf94ff89b80345c155b1",
  },
  {
    title: "Integrate weather API",
    description: "Show local weather for better planning in dashboard",
    priority: "Low",
    status: "done",
    dueDate: new Date("2025-08-01"),
    tags: "api,weather,ui",
    inProgress: 100,
    user: "6894bf94ff89b80345c155b1",
  },
  {
    title: "Create theme switcher",
    description: "Allow users to toggle between light/dark themes",
    priority: "Medium",
    status: "todo",
    dueDate: new Date("2025-08-14"),
    tags: "theme,ux,frontend",
    inProgress: 0,
    user: "6894bf94ff89b80345c155b1",
  },
  {
    title: "Update README and documentation",
    description: "Add new setup instructions and contribution guide",
    priority: "Low",
    status: "done",
    dueDate: new Date("2025-08-02"),
    tags: "docs,readme,community",
    inProgress: 100,
    user: "6894bf94ff89b80345c155b1",
  },

  // Content Creator
  {
    title: "Write blog on productivity tools",
    description: "Include FocusHub and other top 5 tools in 2025",
    priority: "High",
    status: "in_Progress",
    dueDate: new Date("2025-08-08"),
    tags: "content,blog,productivity",
    inProgress: 50,
    user: "6894bff1ff89b80345c155b7",
  },
  {
    title: "Record FocusHub walkthrough",
    description: "Screen record full app demo for YouTube",
    priority: "Medium",
    status: "todo",
    dueDate: new Date("2025-08-11"),
    tags: "video,content,youtube",
    inProgress: 0,
    user: "6894bff1ff89b80345c155b7",
  },
  {
    title: "Create infographic for dashboard features",
    description: "Design a modern infographic for social media",
    priority: "Medium",
    status: "in_Progress",
    dueDate: new Date("2025-08-16"),
    tags: "design,infographic,marketing",
    inProgress: 30,
    user: "6894bff1ff89b80345c155b7",
  },
  {
    title: "Schedule Instagram reels",
    description: "Create and queue 5 reels for this week",
    priority: "Low",
    status: "done",
    dueDate: new Date("2025-08-03"),
    tags: "social,ig,reels",
    inProgress: 100,
    user: "6894bff1ff89b80345c155b7",
  },
  {
    title: "Respond to YouTube comments",
    description: "Engage with viewers to improve retention",
    priority: "Low",
    status: "todo",
    dueDate: new Date("2025-08-13"),
    tags: "community,youtube,engagement",
    inProgress: 0,
    user: "6894bff1ff89b80345c155b7",
  }
];


module.exports = sampleTasks;